### ISSUE TITLE
Support for Resharper 9

### ISSUE THREAD

**Issue by pakrym** [controlflow/resharper-gotoword#11]
It would be great to have

**Comment by mvonballmo** [comment]
Any update on support for R# 9? I'm quite attached to this extension and miss it already.

**Comment by DanielLaberge** [comment]
+1 This feature is a must-have and is sorely missed from R# 9 right now.

**Comment by jeaneliebreton** [comment]
+1

**Comment by lookforit** [comment]
+1

**Comment by laurentkempe** [comment]
Would be great to have it! :+1:

**Comment by veraciousnottaken** [comment]
I miss this extension

**Comment by clijiac** [comment]
+1
any news for this?

**Comment by dcumin39** [comment]
+1
in the meantime has anyone found an alternative that works.  I tried building and installing locally but couldn't get the local nuget package working.

**Comment by dcumin39** [comment]
So, It's nowhere near as nice but it is better than the Ctrl + shift + f we are stuck with:
https://visualstudiogallery.msdn.microsoft.com/06f39a31-20ce-408c-afee-8a02b484db1c

**Comment by controlflow** [comment]
Let me clarify the situation with "Go to word" plugin:
* Unfortunately, I still have no free time to finish `v2` version of this plugin;

Long version:
* Plugin was initially made via pure hacks into ReSharper infrastructure;
* Navigation APIs are full of breaking changes (in a good directions) in ReSharper 9. It was hard to simply port `8.x` version, because some hacks stops working, so I abandoned 8.x version and started complete rewrite - version 2.0 of plugin, with less hacks;
* Unfortunately, ReSharper 9.x releases were quite stressful for me, I still has no free time to do some work on this plugin;
* Plugin works in `8.x`, but experience still sucks comparing to VisualStudio's `Ctrl+F`. I was planning to add support for recent searches list (just like in ReSharper's Go To Everything `Ctrl+T`), as well as immediate search in current file (so you can see occurrences highlighted in editor just like in `Ctrl+F`). I implemented immediate search and was playing with editor performance when tons of occurrences displayed;
* I was planning to improve solution traverse algorithm (current file -> files in open tabs -> current folder -> folder one level up -> ... -> project -> dependent projects -> projects depending on current project -> solution), this can possibly make typical search faster;
* Preview tabs support, regex support and etc were my list;
* Talking about "quadruple `Ctrl+T`": ReSharper 9.x plugins are free from all the VS integration issues we have in 8.x plugins - I can finally register go to word's own hotkey and it will be preserved between VS runs;
* In ReSharper 9.0 we introduced asynchronous "Find usages" experience (so you can continue navigating or even editing code while complex search is done in background) - this maybe really nice to have in 'Go to word' too;
* In ReSharper team, we have plans to have textual search included in the next major version (ReSharper 10.0 or 9.2, no comments on estimates). I have no idea will it be this plugin finished and bundled into R# or some colleague of mine implement something different, but we definitely look at your feedback and want such functionality bundled with R#.

So, no promises from me right now, but I'm aware of your feedback!

**Comment by dcumin39** [comment]
Thanks.  Really appreciate the work you do!

**Comment by pfattisc** [comment]
+1

**Comment by rasmus** [comment]
+1

**Comment by themetis** [comment]
+1

**Comment by Tyube** [comment]
+1

**Comment by Arkayus** [comment]
+1

**Comment by dcumin39** [comment]
I checked  and this is out of scope for 9.2
http://blog.jetbrains.com/dotnet/2015/06/15/resharper-9-2-expected-in-august-will-support-visual-studio-2015-rtm-windows-10/

**Comment by StephenTung-CR** [comment]
+1

**Comment by mvonballmo** [comment]
+1

With 9.2 out now, how are things looking for integration of GoToWord functionality in R# 10? Solutions like the one mentioned by @dcumin39 ([Sando](https://visualstudiogallery.msdn.microsoft.com/06f39a31-20ce-408c-afee-8a02b484db1c)) are sub-optimal because they require yet building and maintaining yet another index in-memory.

With so much more client-side development going on in Visual Studio, with dynamic languages and data-binding languages that use name-matching for data-binding, GoToWord is more and more essential. Sure, ReSharper can continue to integrate native support for finding such references, but until that happens, we're stuck with the inferior Find-in-Files dialog or other extensions that increase the memory pressure for larger solutions.

Thanks again for a great plugin that I still use every day (in case you're wondering, I'm not on R# 9.x yet because of issues with the test-runner and also missing support for the StyleCop extension).

**Comment by dcumin39** [comment]
Opened up some old code today which still used vs 2013 and resharper 8.  I forget just how amazing this extension was.  Next to refactoring methods/classes and extracting parameters this was probably the most useful/used feature.  Still no hint of a comparable feature in Resharper 10.    I have since updated to Entrian Source Search which allows for better searching than ctrl + shift + f

http://entrian.com/source-search/

![image](https://cloud.githubusercontent.com/assets/11169191/10399130/c7cf9d9c-6e7e-11e5-9138-fce3e2faa65e.png)

**Comment by slowkot** [comment]
+1

**Comment by hrannzo** [comment]
+1

**Comment by rdumont** [comment]
We have ReSharper 10 now! Will it be easier to me the extension compatible with it?

**Comment by dcumin39** [comment]
Any updates on Resharper 11 having this feature?  If not, has anyone found a viable alternative.

**Comment by dcumin39** [comment]
So I created a ticket: https://youtrack.jetbrains.com/issue/RSRP-446619  

I did not see anyone else requesting this feature.  Might help if it got a couple upvotes
https://youtrack.jetbrains.com/issues/RSRP?q=text+search+%23Feature+%23Unresolved

**Comment by RazmikDev** [comment]
Guys, please, welcome to try ReSharper [2016.2 EAP 9 and above](https://confluence.jetbrains.com/display/ReSharper/ReSharper+2016.2+EAP) and check out new "Go to text" feature available by "`Ctrl+T,T,T`" 🎱

**Comment by controlflow** [comment]
![img](http://media.giphy.com/media/iPTTjEt19igne/giphy.gif)
